version: "3"

services:
  zeldon-site:
    image: zeldon-site:latest
    container_name: zeldon-site
    build:
      context: .
      dockerfile: config/Dockerfile
    ports:
      - "3123:80"
    restart: unless-stopped
    volumes:
      - ./config/nginx.conf:/etc/nginx/conf.d/default.conf:ro
